//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BITSManager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BITSManager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add file to job.
        /// </summary>
        public static string AddFileToJob {
            get {
                return ResourceManager.GetString("AddFileToJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create New Job.
        /// </summary>
        public static string CreateNewJob {
            get {
                return ResourceManager.GetString("CreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Name.
        /// </summary>
        public static string CreateNewJobJobName {
            get {
                return ResourceManager.GetString("CreateNewJobJobName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string CreateNewJobJobType {
            get {
                return ResourceManager.GetString("CreateNewJobJobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string DialogCancel {
            get {
                return ResourceManager.GetString("DialogCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Local file.
        /// </summary>
        public static string DialogFile {
            get {
                return ResourceManager.GetString("DialogFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string DialogOK {
            get {
                return ResourceManager.GetString("DialogOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote URL.
        /// </summary>
        public static string DialogUrl {
            get {
                return ResourceManager.GetString("DialogUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add file to job.
        /// </summary>
        public static string ErrorCantAddFile {
            get {
                return ResourceManager.GetString("ErrorCantAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to BITS.
        /// </summary>
        public static string ErrorCantConnectToBits {
            get {
                return ResourceManager.GetString("ErrorCantConnectToBits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to connect to BITS with exception {0:X} {1}.
        /// </summary>
        public static string ErrorCantConnectToBitsException {
            get {
                return ResourceManager.GetString("ErrorCantConnectToBitsException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can only set DOWNLOAD jobs as DYNAMIC.
        /// </summary>
        public static string ErrorCantSetDynamic {
            get {
                return ResourceManager.GetString("ErrorCantSetDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The local file must not be blank.
        /// </summary>
        public static string ErrorEmptyLocalFile {
            get {
                return ResourceManager.GetString("ErrorEmptyLocalFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The remote URL must not be blank.
        /// </summary>
        public static string ErrorEmptyRemoteUrl {
            get {
                return ResourceManager.GetString("ErrorEmptyRemoteUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You must be an administrator to read job information for all users.
        /// </summary>
        public static string ErrorInsufficientPrivilegesMessage {
            get {
                return ResourceManager.GetString("ErrorInsufficientPrivilegesMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Insufficient Privileges.
        /// </summary>
        public static string ErrorInsufficientPrivilegesTitle {
            get {
                return ResourceManager.GetString("ErrorInsufficientPrivilegesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: {0}.
        /// </summary>
        public static string ErrorMessage {
            get {
                return ResourceManager.GetString("ErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on {0}.
        /// </summary>
        public static string ErrorWhenTitle {
            get {
                return ResourceManager.GetString("ErrorWhenTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string FileByteProgress {
            get {
                return ResourceManager.GetString("FileByteProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Details.
        /// </summary>
        public static string FileDetails {
            get {
                return ResourceManager.GetString("FileDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Response.
        /// </summary>
        public static string FileHttpResponseData {
            get {
                return ResourceManager.GetString("FileHttpResponseData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not available).
        /// </summary>
        public static string FileHttpResponseDataNotAvailable {
            get {
                return ResourceManager.GetString("FileHttpResponseDataNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Filename.
        /// </summary>
        public static string FileLocal {
            get {
                return ResourceManager.GetString("FileLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string FileOpen {
            get {
                return ResourceManager.GetString("FileOpen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open the completed file.
        /// </summary>
        public static string FileOpenTooltip {
            get {
                return ResourceManager.GetString("FileOpenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} bytes.
        /// </summary>
        public static string FileProgressByteCount {
            get {
                return ResourceManager.GetString("FileProgressByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} bytes.
        /// </summary>
        public static string FileProgressByteCountUnknown {
            get {
                return ResourceManager.GetString("FileProgressByteCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to URL	.
        /// </summary>
        public static string FileRemote {
            get {
                return ResourceManager.GetString("FileRemote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication Type.
        /// </summary>
        public static string JobAuthScheme {
            get {
                return ResourceManager.GetString("JobAuthScheme", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BASIC.
        /// </summary>
        public static string JobAuthSchemeBasic {
            get {
                return ResourceManager.GetString("JobAuthSchemeBasic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Digest.
        /// </summary>
        public static string JobAuthSchemeDigest {
            get {
                return ResourceManager.GetString("JobAuthSchemeDigest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nego.
        /// </summary>
        public static string JobAuthSchemeNegotiate {
            get {
                return ResourceManager.GetString("JobAuthSchemeNegotiate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NTLM.
        /// </summary>
        public static string JobAuthSchemeNtlm {
            get {
                return ResourceManager.GetString("JobAuthSchemeNtlm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passport.
        /// </summary>
        public static string JobAuthSchemePassport {
            get {
                return ResourceManager.GetString("JobAuthSchemePassport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add File.
        /// </summary>
        public static string JobButtonAddFile {
            get {
                return ResourceManager.GetString("JobButtonAddFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string JobButtonCancel {
            get {
                return ResourceManager.GetString("JobButtonCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete.
        /// </summary>
        public static string JobButtonComplete {
            get {
                return ResourceManager.GetString("JobButtonComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resume.
        /// </summary>
        public static string JobButtonResume {
            get {
                return ResourceManager.GetString("JobButtonResume", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspend.
        /// </summary>
        public static string JobButtonSuspend {
            get {
                return ResourceManager.GetString("JobButtonSuspend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Byte Progress.
        /// </summary>
        public static string JobByteProgress {
            get {
                return ResourceManager.GetString("JobByteProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add file {0} because {1}.
        /// </summary>
        public static string JobCantAddFileMessage {
            get {
                return ResourceManager.GetString("JobCantAddFileMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error: Unable to add file.
        /// </summary>
        public static string JobCantAddFileTitle {
            get {
                return ResourceManager.GetString("JobCantAddFileTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost	.
        /// </summary>
        public static string JobCost {
            get {
                return ResourceManager.GetString("JobCost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        public static string JobCostAlways {
            get {
                return ResourceManager.GetString("JobCostAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cost	.
        /// </summary>
        public static string JobCostFlag {
            get {
                return ResourceManager.GetString("JobCostFlag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No surcharge.
        /// </summary>
        public static string JobCostNoSurcharge {
            get {
                return ResourceManager.GetString("JobCostNoSurcharge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string JobCostNotAvailable {
            get {
                return ResourceManager.GetString("JobCostNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not roaming.
        /// </summary>
        public static string JobCostNotRoaming {
            get {
                return ResourceManager.GetString("JobCostNotRoaming", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Standard.
        /// </summary>
        public static string JobCostStandard {
            get {
                return ResourceManager.GetString("JobCostStandard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unrestricted.
        /// </summary>
        public static string JobCostUnrestricted {
            get {
                return ResourceManager.GetString("JobCostUnrestricted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created On.
        /// </summary>
        public static string JobCreationTime {
            get {
                return ResourceManager.GetString("JobCreationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Custom HTTP.
        /// </summary>
        public static string JobCustomHeaders {
            get {
                return ResourceManager.GetString("JobCustomHeaders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP headers not available because {0}.
        /// </summary>
        public static string JobCustomHeadersException {
            get {
                return ResourceManager.GetString("JobCustomHeadersException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string JobCustomHeadersNotAvailable {
            get {
                return ResourceManager.GetString("JobCustomHeadersNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (no custom headers set).
        /// </summary>
        public static string JobCustomHeadersNotSet {
            get {
                return ResourceManager.GetString("JobCustomHeadersNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string JobDescription {
            get {
                return ResourceManager.GetString("JobDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Details.
        /// </summary>
        public static string JobDetails {
            get {
                return ResourceManager.GetString("JobDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string JobDisplayName {
            get {
                return ResourceManager.GetString("JobDisplayName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Context	.
        /// </summary>
        public static string JobErrorContext {
            get {
                return ResourceManager.GetString("JobErrorContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error Count.
        /// </summary>
        public static string JobErrorCount {
            get {
                return ResourceManager.GetString("JobErrorCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string JobErrorDescription {
            get {
                return ResourceManager.GetString("JobErrorDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t read error details.
        /// </summary>
        public static string JobErrorException {
            get {
                return ResourceManager.GetString("JobErrorException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HRESULT.
        /// </summary>
        public static string JobErrorHRESULT {
            get {
                return ResourceManager.GetString("JobErrorHRESULT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No errors.
        /// </summary>
        public static string JobErrorNoErrors {
            get {
                return ResourceManager.GetString("JobErrorNoErrors", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get error details.
        /// </summary>
        public static string JobErrorWhenError {
            get {
                return ResourceManager.GetString("JobErrorWhenError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Progress.
        /// </summary>
        public static string JobFileProgress {
            get {
                return ResourceManager.GetString("JobFileProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Flags	.
        /// </summary>
        public static string JobFlags {
            get {
                return ResourceManager.GetString("JobFlags", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dynamic.
        /// </summary>
        public static string JobFlagsDynamic {
            get {
                return ResourceManager.GetString("JobFlagsDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High-performance.
        /// </summary>
        public static string JobFlagsHighPerformance {
            get {
                return ResourceManager.GetString("JobFlagsHighPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No flags set.
        /// </summary>
        public static string JobFlagsNoneSet {
            get {
                return ResourceManager.GetString("JobFlagsNoneSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string JobFlagsNotAvailable {
            get {
                return ResourceManager.GetString("JobFlagsNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On-demand mode.
        /// </summary>
        public static string JobFlagsOnDemandMode {
            get {
                return ResourceManager.GetString("JobFlagsOnDemandMode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP Method.
        /// </summary>
        public static string JobHttpMethod {
            get {
                return ResourceManager.GetString("JobHttpMethod", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to HTTP method not available because {0}.
        /// </summary>
        public static string JobHttpMethodException {
            get {
                return ResourceManager.GetString("JobHttpMethodException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not available.
        /// </summary>
        public static string JobHttpMethodNotAvailable {
            get {
                return ResourceManager.GetString("JobHttpMethodNotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to (not set).
        /// </summary>
        public static string JobHttpMethodNotSet {
            get {
                return ResourceManager.GetString("JobHttpMethodNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modified On.
        /// </summary>
        public static string JobModificationTime {
            get {
                return ResourceManager.GetString("JobModificationTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Owner.
        /// </summary>
        public static string JobOwner {
            get {
                return ResourceManager.GetString("JobOwner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string JobPassword {
            get {
                return ResourceManager.GetString("JobPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Priority	.
        /// </summary>
        public static string JobPriority {
            get {
                return ResourceManager.GetString("JobPriority", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        public static string JobPriorityForeground {
            get {
                return ResourceManager.GetString("JobPriorityForeground", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string JobPriorityHigh {
            get {
                return ResourceManager.GetString("JobPriorityHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string JobPriorityLow {
            get {
                return ResourceManager.GetString("JobPriorityLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        public static string JobPriorityNormal {
            get {
                return ResourceManager.GetString("JobPriorityNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Progress.
        /// </summary>
        public static string JobProgress {
            get {
                return ResourceManager.GetString("JobProgress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} bytes.
        /// </summary>
        public static string JobProgressByteCount {
            get {
                return ResourceManager.GetString("JobProgressByteCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} bytes.
        /// </summary>
        public static string JobProgressByteCountUnknown {
            get {
                return ResourceManager.GetString("JobProgressByteCountUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0:N0} of {1:N0} files.
        /// </summary>
        public static string JobProgressFileCount {
            get {
                return ResourceManager.GetString("JobProgressFileCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job is Dynamic.
        /// </summary>
        public static string JobPropertyDynamic {
            get {
                return ResourceManager.GetString("JobPropertyDynamic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job is High Performance.
        /// </summary>
        public static string JobPropertyHighPerformance {
            get {
                return ResourceManager.GetString("JobPropertyHighPerformance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job State.
        /// </summary>
        public static string JobState {
            get {
                return ResourceManager.GetString("JobState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acknowledged.
        /// </summary>
        public static string JobStateAcknowledged {
            get {
                return ResourceManager.GetString("JobStateAcknowledged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancelled.
        /// </summary>
        public static string JobStateCancelled {
            get {
                return ResourceManager.GetString("JobStateCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting.
        /// </summary>
        public static string JobStateConnecting {
            get {
                return ResourceManager.GetString("JobStateConnecting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string JobStateError {
            get {
                return ResourceManager.GetString("JobStateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queued.
        /// </summary>
        public static string JobStateQueued {
            get {
                return ResourceManager.GetString("JobStateQueued", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Suspended.
        /// </summary>
        public static string JobStateSuspended {
            get {
                return ResourceManager.GetString("JobStateSuspended", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tranferred.
        /// </summary>
        public static string JobStateTransferred {
            get {
                return ResourceManager.GetString("JobStateTransferred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transferring.
        /// </summary>
        public static string JobStateTransferring {
            get {
                return ResourceManager.GetString("JobStateTransferring", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transient Error.
        /// </summary>
        public static string JobStateTransientError {
            get {
                return ResourceManager.GetString("JobStateTransientError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job State Unknown ({0}).
        /// </summary>
        public static string JobStateUnknown {
            get {
                return ResourceManager.GetString("JobStateUnknown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to not set.
        /// </summary>
        public static string JobTimeNotSet {
            get {
                return ResourceManager.GetString("JobTimeNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Completed On.
        /// </summary>
        public static string JobTransferCompletionTime {
            get {
                return ResourceManager.GetString("JobTransferCompletionTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Job Type.
        /// </summary>
        public static string JobType {
            get {
                return ResourceManager.GetString("JobType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        public static string JobTypeDownload {
            get {
                return ResourceManager.GetString("JobTypeDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string JobTypeUpload {
            get {
                return ResourceManager.GetString("JobTypeUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload Reply.
        /// </summary>
        public static string JobTypeUploadReply {
            get {
                return ResourceManager.GetString("JobTypeUploadReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string JobUserName {
            get {
                return ResourceManager.GetString("JobUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New _Job.
        /// </summary>
        public static string MenuCreateNewJob {
            get {
                return ResourceManager.GetString("MenuCreateNewJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Jobs.
        /// </summary>
        public static string MenuJob {
            get {
                return ResourceManager.GetString("MenuJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _All Users.
        /// </summary>
        public static string MenuJobsAllUsers {
            get {
                return ResourceManager.GetString("MenuJobsAllUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quic_k File Download.
        /// </summary>
        public static string MenuQuickFileDownload {
            get {
                return ResourceManager.GetString("MenuQuickFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to _Refresh.
        /// </summary>
        public static string MenuRefresh {
            get {
                return ResourceManager.GetString("MenuRefresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quick file download.
        /// </summary>
        public static string QuickFileDownload {
            get {
                return ResourceManager.GetString("QuickFileDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BITS Manager.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception {0} type {1}.
        /// </summary>
        public static string UnhandledExceptionMessage {
            get {
                return ResourceManager.GetString("UnhandledExceptionMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled Exception.
        /// </summary>
        public static string UnhandledExceptionTitle {
            get {
                return ResourceManager.GetString("UnhandledExceptionTitle", resourceCulture);
            }
        }
    }
}
